import {slide,legalMoves,type Direction} from '../2048/game.ts';
export function features(board:number[]){const logs=board.map(v=>v?Math.log2(v):0);const empty=board.filter(v=>!v).length;let roughness=0,merges=0,disorder=0;for(let axis=0;axis<2;axis++)for(let line=0;line<4;line++){const values=Array.from({length:4},(_,i)=>logs[axis?i*4+line:line*4+i]);let up=0,down=0;for(let i=0;i<3;i++){const a=values[i],b=values[i+1];if(a&&b){roughness+=Math.abs(a-b);if(a===b)merges++;}up+=Math.max(0,b-a);down+=Math.max(0,a-b);}disorder+=Math.min(up,down);}const maximum=Math.max(...board);const corner=[0,3,12,15].some(i=>board[i]===maximum);return {empty,mergePairs:merges,roughness,disorder,maxTile:maximum,maxInCorner:corner};}
export function evaluateBoard(board:number[]){const f=features(board);return f.empty*270+f.mergePairs*45-f.roughness*12-f.disorder*75+(f.maxInCorner?Math.log2(f.maxTile||1)*80:0);}
// Exact chance expansion: every empty cell, 2 at 90% and 4 at 10%.
// Two player moves: candidate move -> random tile -> best next move -> random tile -> heuristic.
function chance(board:number[],remaining:number):number{const empty=board.map((v,i)=>v===0?i:-1).filter(i=>i>=0);if(!empty.length)return player(board,remaining);let total=0;for(const index of empty)for(const [tile,weight] of [[2,.9],[4,.1]]){const next=board.slice();next[index]=tile;total+=weight*player(next,remaining)/empty.length;}return total;}
function player(board:number[],remaining:number):number{const legal=legalMoves(board);if(!legal.length)return -100000;if(remaining===0)return evaluateBoard(board);return Math.max(...legal.map(d=>{const next=slide(board,d);return next.gain*.5+chance(next.board,remaining-1);}));}
export function analyze(board:number[]){return legalMoves(board).map(direction=>{const next=slide(board,direction);return {direction,expectedValue:Math.round((next.gain*.5+chance(next.board,1))*100)/100,immediateGain:next.gain,features:features(next.board),board:next.board};}).sort((a,b)=>b.expectedValue-a.expectedValue);}
export type Analysis=ReturnType<typeof analyze>;
