import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {ensureJevCatalog,newJevSites} from '../db/jev-catalog.ts';
function database(){const sqlite=new DatabaseSync(':memory:');for(const file of ['0000_high_runaways.sql','0001_happy_charles_xavier.sql'])sqlite.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));const api={prepare(sql){let values=[];return {bind(...args){values=args;return this},first(){return sqlite.prepare(sql).get(...values)||null},run(){return sqlite.prepare(sql).run(...values)}}},async batch(statements){sqlite.exec('BEGIN');try{const result=statements.map(s=>s.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return {sqlite,api};}
test('catalog install is one-time and preserves later edits/deletions',async()=>{const {sqlite,api}=database();try{await Promise.all([ensureJevCatalog(api),ensureJevCatalog(api)]);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,9);sqlite.prepare('UPDATE sites SET name=? WHERE id=?').run('My name','jev-reviews');sqlite.prepare('DELETE FROM sites WHERE id=?').run('jev-tasks');await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT name FROM sites WHERE id=?').get('jev-reviews').name,'My name');assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,8);}finally{sqlite.close();}});
test('existing registration for the same URL is not overwritten or duplicated',async()=>{const {sqlite,api}=database();try{sqlite.prepare('INSERT INTO sites VALUES(?,?,?,?,?,?,?,?)').run('custom-id','Existing review demo','https://demo-atlas-kouki.koki-uchida.chatgpt.site/jev/reviews','その他','my description','mine','準備中','2026-01-01');await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,9);assert.equal(sqlite.prepare('SELECT name FROM sites WHERE id=?').get('custom-id').name,'Existing review demo');}finally{sqlite.close();}});

test('new release installs after earlier collection, without resurrecting deleted demos',async()=>{const {sqlite,api}=database();try{sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-use-cases-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-harness-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-browser-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-shopping-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-2048-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-2048-plus-2026-09-21','2026-09-21');await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,1);assert.equal(sqlite.prepare('SELECT id FROM sites').get().id,'qwen-image');sqlite.prepare('DELETE FROM sites').run();await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,0);}finally{sqlite.close();}});
