import test from 'node:test';import assert from 'node:assert/strict';
import {slide,newGame,move,legalMoves,finished} from '../app/jev/2048/game.ts';
import {evaluate2048} from '../app/jev/2048/engine.ts';
const row=(values)=>[...values,...Array(12).fill(0)];
test('merges once per tile, scores correctly and respects direction',()=>{assert.deepEqual(slide(row([2,2,2,2]),'left'),{board:row([4,4,0,0]),gain:8,changed:true});assert.deepEqual(slide(row([2,2,4,0]),'left').board,row([4,4,0,0]));assert.deepEqual(slide(row([2,2,4,0]),'right').board,row([0,0,4,4]));const vertical=Array(16).fill(0);vertical[0]=vertical[4]=2;assert.equal(slide(vertical,'down').board[12],4);assert.equal(slide(vertical,'up').board[0],4);});
test('same seed and moves reproduce the full game; invalid moves consume nothing',()=>{let a=newGame(42),b=newGame(42);assert.deepEqual(a,b);for(let i=0;i<50&&!finished(a);i++){const d=legalMoves(a.board)[0];a=move(a,d);b=move(b,d);assert.deepEqual(a,b);}const g={board:row([2,0,0,0]),score:0,moves:0,rng:123};assert.strictEqual(move(g,'left'),g);assert.equal(move(g,'right').moves,1);});
test('full board with a merge remains playable; checkerboard ends; 2048 wins',()=>{const checker=[2,4,2,4,4,2,4,2,2,4,2,4,4,2,4,2];const g={board:checker,score:0,moves:0,rng:1};assert.equal(finished(g),true);assert.equal(finished({...g,board:[2,2,...checker.slice(2)]}),false);assert.equal(finished({...g,board:row([2048,0,0,0])}),true);});
test('API returns only legal directions and never sends keys in state',async()=>{const board=row([2,0,0,0]);const output=await evaluate2048({board,apiKey:'test-only'},async(url,init)=>{const body=JSON.parse(init.body);assert.deepEqual(Object.keys(body.questions.direction.criteria),['right','down']);assert.ok(!init.body.includes('test-only'));return Response.json({answers:{direction:{type:'choice',choice:'right',confidence:.8,probabilities:{right:.8,down:.2}}}});});assert.equal(output.choice,'right');await assert.rejects(()=>evaluate2048({board,apiKey:'x'},async()=>Response.json({answers:{direction:{type:'choice',choice:'left',confidence:.8,probabilities:{}}}})),e=>e.status===502);});
test('invalid and completed boards fail before API calls',async()=>{for(const board of [Array(15).fill(0),row([3,0,0,0]),row([2048,0,0,0])])await assert.rejects(()=>evaluate2048({board,apiKey:'x'},()=>{throw Error('must not call')}),e=>e.status===400);});
