import test from 'node:test';import assert from 'node:assert/strict';
import {newGame,move,legalMoves} from '../app/jev/2048/game.ts';
import {analyze,features} from '../app/jev/2048-plus/search.ts';
import {finished} from '../app/jev/2048-plus/game.ts';
import {evaluatePlus} from '../app/jev/2048-plus/engine.ts';
test('search returns only legal moves in ranked order without changing the board',()=>{const game=newGame(2048),before=game.board.slice();const ranked=analyze(game.board);assert.deepEqual(new Set(ranked.map(a=>a.direction)),new Set(legalMoves(game.board)));assert.deepEqual(game.board,before);assert.deepEqual(analyze(game.board),ranked);assert.ok(ranked.every((r,i)=>Number.isFinite(r.expectedValue)&&(!i||ranked[i-1].expectedValue>=r.expectedValue)));});
test('terminal boards return no actions and features describe actual cells',()=>{assert.ok(analyze([2048,...Array(15).fill(0)]).length>0);assert.deepEqual(analyze([2,4,2,4,4,2,4,2,2,4,2,4,4,2,4,2]),[]);const f=features([8,8,...Array(14).fill(0)]);assert.equal(f.empty,14);assert.equal(f.mergePairs,1);assert.equal(f.maxInCorner,true);});
test('enhanced API includes lookahead but not seed or key, and preserves returned confidence',async()=>{const game=newGame(3);const legal=legalMoves(game.board);const out=await evaluatePlus({board:game.board,apiKey:'secret-test'},async(url,init)=>{const body=JSON.parse(init.body);assert.ok(!init.body.includes('secret-test'));const state=JSON.parse(body.state);assert.equal(state.lookahead.player_moves,2);assert.equal(state.seed,undefined);assert.equal(state.lookahead.ranked_moves.length,legal.length);return Response.json({answers:{direction:{type:'choice',choice:legal[0],confidence:.31,probabilities:Object.fromEntries(legal.map(d=>[d,1/legal.length]))}}});});assert.equal(out.confidence,.31);assert.ok(out.analysis.length);});
test('search can play a deterministic sequence of valid moves',()=>{let g=newGame(42);for(let i=0;i<15;i++){const a=analyze(g.board);assert.ok(a.length);const next=move(g,a[0].direction);assert.equal(next.moves,g.moves+1);g=next;}assert.ok(g.score>0);});

test('2048 and 4096 continue; merged tiles and score progress beyond the old target',()=>{const game={board:[2048,2048,...Array(14).fill(0)],score:0,moves:0,rng:1};assert.equal(finished(game),false);const next=move(game,'left');assert.equal(next.board[0],4096);assert.equal(next.score,4096);assert.equal(finished(next),false);assert.ok(analyze(next.board).length);const dead={...game,board:[4096,2,4,2,2,4,2,4,4,2,4,2,2,4,2,4]};assert.equal(finished(dead),true);assert.deepEqual(analyze(dead.board),[]);});
test('both Jev strategies accept 4096 boards and reject truly terminal boards',async()=>{for(const mode of ['baseline','enhanced']){const board=[4096,...Array(15).fill(0)];const result=await evaluatePlus({board,apiKey:'x',mode},async()=>Response.json({answers:{direction:{type:'choice',choice:'right',confidence:.5,probabilities:{right:.5,down:.5}}}}));assert.equal(result.choice,'right');await assert.rejects(()=>evaluatePlus({board:[4096,2,4,2,2,4,2,4,4,2,4,2,2,4,2,4],apiKey:'x',mode},()=>{throw Error('must not call')}),e=>e.status===400);}});
