import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {ensureJevCatalog,newJevSites} from '../db/jev-catalog.ts';
function database(){const sqlite=new DatabaseSync(':memory:');for(const file of ['0000_high_runaways.sql','0001_happy_charles_xavier.sql'])sqlite.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));const api={prepare(sql){let values=[];return {bind(...args){values=args;return this},first(){return sqlite.prepare(sql).get(...values)||null},run(){return sqlite.prepare(sql).run(...values)}}},async batch(statements){sqlite.exec('BEGIN');try{const result=statements.map(s=>s.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return {sqlite,api};}
test('catalog install is one-time and preserves later edits/deletions',async()=>{const {sqlite,api}=database();try{await Promise.all([ensureJevCatalog(api),ensureJevCatalog(api)]);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,21);sqlite.prepare('UPDATE sites SET name=? WHERE id=?').run('My name','jev-reviews');sqlite.prepare('DELETE FROM sites WHERE id=?').run('jev-tasks');await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT name FROM sites WHERE id=?').get('jev-reviews').name,'My name');assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,20);}finally{sqlite.close();}});
test('existing registration for the same URL is not overwritten or duplicated',async()=>{const {sqlite,api}=database();try{sqlite.prepare('INSERT INTO sites VALUES(?,?,?,?,?,?,?,?)').run('custom-id','Existing review demo','https://demo-atlas-kouki.koki-uchida.chatgpt.site/jev/reviews','その他','my description','mine','準備中','2026-01-01');await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,21);assert.equal(sqlite.prepare('SELECT name FROM sites WHERE id=?').get('custom-id').name,'Existing review demo');}finally{sqlite.close();}});

test('new release installs after earlier collection, without resurrecting deleted demos',async()=>{const {sqlite,api}=database();try{sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-use-cases-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-harness-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-browser-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-shopping-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-2048-2026-09-21','2026-09-21');sqlite.prepare('INSERT INTO catalog_installs VALUES(?,?)').run('jev-2048-plus-2026-09-21','2026-09-21');await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,13);assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM sites WHERE id IN ('qwen-image','qwen-comfyui','qwen-inference','qwen-prompt-rewrite','jev-evals')").get().n,5);sqlite.prepare('DELETE FROM sites').run();await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sites').get().n,0);}finally{sqlite.close();}});
test('Colab descriptions refresh defaults but preserve owner text',async()=>{const {sqlite,api}=database();try{await ensureJevCatalog(api);sqlite.prepare('DELETE FROM catalog_installs WHERE key=?').run('colab-labs-descriptions-2026-09-21');sqlite.prepare('UPDATE sites SET description=? WHERE id=?').run('生成・編集の4工程をたどり、公式PNGのアルファを解析。ComfyUIの透過生成を学ぶデモ。','qwen-comfyui');sqlite.prepare('UPDATE sites SET description=? WHERE id=?').run('owner customized','jev-evals');await ensureJevCatalog(api);assert.match(sqlite.prepare('SELECT description FROM sites WHERE id=?').get('qwen-comfyui').description,/Colab/);assert.equal(sqlite.prepare('SELECT description FROM sites WHERE id=?').get('jev-evals').description,'owner customized');}finally{sqlite.close();}});

test('September 22 labs install once and preserve owner edits/deletions',async()=>{const {sqlite,api}=database();try{await ensureJevCatalog(api);for(const id of ['grok-lab','kev-lab','python-workers-lab','langsmith-jev-lab'])assert.ok(sqlite.prepare('SELECT id FROM sites WHERE id=?').get(id));sqlite.prepare('DELETE FROM sites WHERE id=?').run('kev-lab');sqlite.prepare('UPDATE sites SET description=? WHERE id=?').run('custom text','grok-lab');await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT id FROM sites WHERE id=?').get('kev-lab'),undefined);assert.equal(sqlite.prepare('SELECT description FROM sites WHERE id=?').get('grok-lab').description,'custom text');}finally{sqlite.close();}});

test('September 23 labs are separate entries and retain owner changes',async()=>{const {sqlite,api}=database();try{await ensureJevCatalog(api);for(const id of ['jev-gateway-lab','grok-bedrock-lab','grok-copilot-lab','mimo-lab'])assert.ok(sqlite.prepare('SELECT id FROM sites WHERE id=?').get(id));sqlite.prepare('DELETE FROM sites WHERE id=?').run('mimo-lab');sqlite.prepare('UPDATE sites SET name=? WHERE id=?').run('Owner name','grok-bedrock-lab');await ensureJevCatalog(api);assert.equal(sqlite.prepare('SELECT id FROM sites WHERE id=?').get('mimo-lab'),undefined);assert.equal(sqlite.prepare('SELECT name FROM sites WHERE id=?').get('grok-bedrock-lab').name,'Owner name');}finally{sqlite.close();}});
