"use client";
import {useState} from 'react';
import {FrontierShell,download} from '../frontier/shared';
import {ggufVariants} from '../frontier/data';
import {CopyBlock} from '../shared';
export default function Page(){const [variant,setVariant]=useState(0),[machine,setMachine]=useState('apple'),[kernel,setKernel]=useState(true),[prompt,setPrompt]=useState('量子化とは何か、日本語で3文で説明してください。'),[fileInfo,setFileInfo]=useState(''),[fileError,setFileError]=useState('');const v=ggufVariants[variant],packed=machine==='apple'&&kernel,quantized=v.id!=='BF16';const code=['# Apple Silicon + 対応するPyTorch / kernelsが必要です。','import torch','from transformers import AutoModelForCausalLM, AutoTokenizer','','repo = "unsloth/Qwen3.5-4B-GGUF"','filename = "Qwen3.5-4B-'+v.id+'.gguf"','tokenizer = AutoTokenizer.from_pretrained(repo, gguf_file=filename)','model = AutoModelForCausalLM.from_pretrained(repo, gguf_file=filename)','messages = [{"role": "user", "content": '+JSON.stringify(prompt)+'}]','inputs = tokenizer.apply_chat_template(messages, tokenize=True,','    add_generation_prompt=True, return_dict=True, return_tensors="pt").to(model.device)','with torch.inference_mode():','    output = model.generate(**inputs, max_new_tokens=256)','print(tokenizer.decode(output[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True))'].join('\n');return <FrontierShell index={3} title="小さく保存。そのまま計算。" lead="GGUFの量子化モデルをTransformersから読み込む。ファイルの大きさ、実行環境、コードのつながりを学びます。" sources={[['Hugging Face / GGUF対応','https://huggingface.co/blog/transformers-llama-cpp-quants'],['Qwen3.5-4B / GGUF','https://huggingface.co/unsloth/Qwen3.5-4B-GGUF']]}>
<div className="lab-grid"><section className="lab-panel"><span className="eyebrow">01 / Qwen3.5-4Bのファイルを比較</span><h2>どこまで小さくする？</h2><label className="lab-label">保存形式<select value={variant} onChange={e=>setVariant(Number(e.target.value))}>{ggufVariants.map((x,i)=><option key={x.id} value={i}>{x.id}</option>)}</select></label><div className="frontier-stat">{v.gb.toFixed(2)} <small>GB</small></div><div className="frontier-meter"><div style={{width:(v.gb/8.42*100)+'%'}}/></div><p>BF16のファイルに対して約{(v.gb/8.42*100).toFixed(0)}%のサイズ。</p><p className="lab-tip">公式記事掲載のファイルサイズ。必要メモリや速度の実測ではありません。量子化は値の精度を減らして保存量を抑える方法で、品質への影響は実際の仕事で確認します。</p></section>
<section className="lab-panel"><span className="eyebrow">02 / 読み込み経路の演習</span><h2>この環境ならどう動く？</h2><label className="lab-label">実行するパソコン<select value={machine} onChange={e=>setMachine(e.target.value)}><option value="apple">Apple Silicon Mac</option><option value="other">Windows / Linux / その他</option></select></label><label className="frontier-check"><input type="checkbox" checked={kernel} onChange={e=>setKernel(e.target.checked)}/>対応するggml / Metalカーネルがある</label><div className="frontier-flow"><span>GGUFファイル</span><span>Transformers</span><span className={packed?'reused':'fresh'}>{!quantized?'非量子化の重みで計算':packed?'圧縮した重みで計算':'対応を確認・必要なら展開'}</span></div><p>{!quantized?'BF16は量子化していない比較用です。小さなビット数で保存する効果はなく、十分な実行メモリが必要です。':packed?'初期対応はApple SiliconのMPSとQwen3.5系。対応カーネルが量子化した重みを扱います。':'この初期の圧縮実行経路の対象外です。展開して読み込むとメモリが増える場合があり、同じ省メモリ・速度を保証しません。'}</p><p className="lab-tip">選択に応じた説明です。あなたの端末を自動診断していません。OS、作業領域、会話用キャッシュも別にメモリを使います。</p></section></div>
<section className="lab-panel release-section"><h2>03 / 自分のMacで実モデルを動かす</h2><p>ブラウザではモデルを読み込みません。以下を対応Macで実行すると、モデルをダウンロードして回答を生成します。最新のTransformersと対応PyTorchが必要です。</p><CopyBlock text={'pip install -U "git+https://github.com/huggingface/transformers.git" kernels'}/><label className="lab-label">モデルへの質問<textarea maxLength={3000} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><CopyBlock text={code} label="Pythonコードをコピー"/><button className="lab-secondary" onClick={()=>download(code,'gguf_demo.py')}>実行用ファイルを保存</button><p className="lab-tip">選択中のファイル：Qwen3.5-4B-{v.id}.gguf。対応カーネルが取得できない場合は警告や展開への切り替えに注意してください。このサイト上ではMac実機の推論結果を計測していません。</p></section>
<section className="lab-panel release-section"><h2>04 / 手元のGGUFファイルを確認</h2><p>先頭24バイトだけをブラウザ内で読みます。ファイルをサーバーへ送信しません。</p><label className="lab-label">GGUFファイル<input type="file" accept=".gguf" onChange={async e=>{setFileInfo('');setFileError('');const f=e.target.files?.[0];if(!f)return;try{const b=await f.slice(0,24).arrayBuffer();if(b.byteLength<24||new TextDecoder().decode(new Uint8Array(b,0,4))!=='GGUF')throw Error('GGUF形式のヘッダーが見つかりません。');const d=new DataView(b),version=d.getUint32(4,true);if(version!==2&&version!==3)throw Error('この確認機能はGGUF v2・v3に対応しています。');setFileInfo(f.name+' / '+(f.size/1e9).toFixed(3)+' GB / GGUF v'+version+' / テンソル数 '+d.getBigUint64(8,true).toString()+' / メタデータ項目 '+d.getBigUint64(16,true).toString());}catch(err){setFileError(err instanceof Error?err.message:'読み取れませんでした。')}}}/></label>{fileError&&<p className="release-message" role="alert">{fileError}</p>}{fileInfo&&<p className="lab-notice" role="status">{fileInfo}</p>}<p className="lab-tip">ヘッダーのみの確認です。ファイル全体の正常性やモデルの実行可否を保証する検査ではありません。</p></section>
</FrontierShell>}
