"use client";
import {useState} from 'react';
import {FrontierShell,KeyInput,useRun,download} from '../frontier/shared';
import {Query,cliCommand} from '../frontier/data';
import {CopyBlock} from '../shared';
const labels={noul:'Yes / No',choice:'担当を選ぶ',score:'再現性を採点'};
const examples={noul:'先月二重に請求されました。重複した分を返金してください。',choice:'アプリのインストールにも失敗しましたが、まず二重請求の返金をお願いします。',score:'設定を開き、通知をオフにして保存する。期待：再起動後もオフ。実際：再起動するとオンに戻る。'};
export default function Page(){const [query,setQuery]=useState<Query>('noul'),[state,setState]=useState(examples.noul),[key,setKey]=useState(''),[result,setResult]=useState<any>(null);const call=useRun();return <FrontierShell index={2} title="文章を、判断できる値へ。" lead="llm-typesafeは、ターミナルからJevを使うプラグイン。自由な回答文ではなく、確率・選択肢・スコアが返る違いを体験します。" sources={[['Simon Willison / llm-typesafe','https://simonwillison.net/2026/Sep/22/llm-typesafe/'],['プラグインの使い方','https://github.com/simonw/llm-typesafe'],['TypeSafe / APIキー','https://console.typesafe.ai']]}>
<div className="release-paths">{(Object.keys(labels) as Query[]).map(q=><button key={q} aria-pressed={query===q} disabled={call.busy} onClick={()=>{setQuery(q);setState(examples[q]);setResult(null)}}><b>{labels[q]}</b><span>{q==='noul'?'返金を求めている確率':q==='choice'?'請求・技術・その他へ分類':'不具合の再現手順を0〜2で評価'}</span></button>)}</div>
<div className="lab-grid"><section className="lab-panel"><h2>01 / 判定する文章</h2><label className="lab-label">入力データ<textarea value={state} maxLength={5000} disabled={call.busy} onChange={e=>{setState(e.target.value);setResult(null)}}/></label><p>{query==='noul'?'質問：返金を明示的に求めていますか？':query==='choice'?'質問：どの担当が対応すべきですか？ 請求と技術が混在する場合は請求を優先。':'質問：この報告だけで不具合を再現できますか？ 0＝手順なし、1＝一部不足、2＝手順と期待・実際がそろう。'}</p><KeyInput label="TypeSafe APIキー" value={key} disabled={call.busy} onChange={setKey}/><p className="lab-tip">「実判定」を押すと入力文と質問をTypeSafeへ送信します。キーは保存しません。GPU不要・APIの利用条件と料金が適用されます。キーの取得に待機登録が必要な場合があります。</p><button className="lab-action" disabled={call.busy||!key.trim()||!state.trim()} onClick={()=>call.run({kind:'cli',query,state,apiKey:key},setResult)}>{call.busy?'Jevが判定中…':'Jevで実判定'}</button>{call.busy&&<button className="lab-secondary" onClick={call.stop}>受信を停止</button>}{call.error&&<p role="alert" className="release-message">{call.error}</p>}</section>
<section className="lab-panel"><h2>02 / 型のある結果</h2>{result?<><p className="lab-notice">実APIの結果 · {result.seconds.toFixed(2)}秒</p>{query==='noul'?<><div className="frontier-stat">{(result.answer.noul*100).toFixed(1)}%</div><p>「返金を求めている」に対応する確率。自動返金は行いません。</p></>:query==='choice'?<><div className="frontier-stat">{({billing:'請求担当',technical:'技術担当',other:'その他'} as Record<string,string>)[result.answer.choice]}</div><p>選択結果と、各担当の確率を返します。</p></>:<><div className="frontier-stat">{result.answer.score.toFixed(2)} / 2</div><p>点数は再現手順の充実度。確率とは異なる値です。</p></>}{result.answer.probabilities&&Object.entries(result.answer.probabilities).map(([label,p])=><div className="release-bars" key={label}><label>{label}<span>{(Number(p)*100).toFixed(1)}%</span></label><progress max={1} value={Number(p)}/></div>)}<CopyBlock text={JSON.stringify(result.answer,null,2)} label="判定JSONをコピー"/></>:<p className="release-empty">実行するとここに値と確率を表示します。架空の判定値は表示しません。</p>}<p className="lab-tip">サイトでは同じ質問をJevのREST APIへ送信します。CLIプログラム自体はブラウザで実行していません。</p></section></div>
<section className="lab-panel release-section"><h2>03 / 同じ入力をターミナルで試す</h2><p>LLM CLIを用意し、以下でプラグインとキーを設定します。キーは対話入力してください。</p><CopyBlock text={'llm install llm-typesafe\nllm keys set typesafe'}/><button className="lab-secondary" onClick={()=>download(state,'message.txt')}>入力文を message.txt として保存</button><p>保存したファイルのフォルダで実行（bash / zsh向け）。入力文をコマンドへ直接埋め込みません。</p><CopyBlock text={cliCommand(query)} label="実行コマンドをコピー"/><p className="lab-tip">CLIでは生のJSONを受け取り、後続の集計や担当振り分けに利用できます。実行時刻やモデル更新でサイトと値が変わる場合があります。</p></section>
</FrontierShell>}
