"use client";
import {useState} from 'react';
import {FrontierShell,KeyInput,useRun,Result} from '../frontier/shared';
import {models,Model,modelIds} from '../frontier/data';
import {Range,CopyBlock} from '../shared';
const initialPrefix='You review data validation specifications. Explain only the requested fields, identify dependency cycles, and distinguish direct from transitive requirements.\nSPEC v1:\n'+Array.from({length:400},(_,i)=>'- rule '+i+': field f'+i+' is required when field f'+((i+1)%400)+' is present. Report the missing field.').join('\n');
export default function Page(){const [model,setModel]=useState<Model>('gpt-6-luna'),[runs,setRuns]=useState(10),[fixed,setFixed]=useState(true),[boundary,setBoundary]=useState(true),[prefix,setPrefix]=useState(initialPrefix),[prompt,setPrompt]=useState('Explain the direct and transitive requirements for f0 in three short sentences.'),[key,setKey]=useState(''),[history,setHistory]=useState<any[]>([]);const call=useRun();const p=models[model],reuse=fixed&&boundary,plain=runs*10000*p.input/1e6,cached=(10000*p.write+(runs-1)*10000*(reuse?p.read:p.write))/1e6;function reset(){setHistory([])}return <FrontierShell index={1} title="毎回読む？ 一度覚える？" lead="長い共通資料をキャッシュに保存して再利用。固定部分の置き方、保存料金、実際のヒットを確かめます。" sources={[['GPT-6 / キャッシュ改善','https://openai.com/index/better-prompt-caching-for-gpt-6'],['OpenAI / キャッシュ仕様','https://developers.openai.com/api/docs/guides/prompt-caching'],['Claude / キャッシュ','https://platform.claude.com/docs/en/build-with-claude/prompt-caching']]}>
<div className="lab-grid"><section className="lab-panel"><span className="eyebrow">01 / 仕組みの演習 · 実測ではありません</span><h2>再利用できる境界を作る</h2><label className="frontier-check"><input type="checkbox" checked={fixed} onChange={e=>setFixed(e.target.checked)}/>共通資料を先頭に固定する</label><label className="frontier-check"><input type="checkbox" checked={boundary} onChange={e=>setBoundary(e.target.checked)}/>共通資料の直後に保存境界を置く</label><div className="frontier-flow">{!fixed&&<span className="fresh">日付・個別の依頼</span>}<span className={reuse?'reused':'fresh'}>共通資料 10,000 tok</span><span>{boundary?'▼ 保存境界':'境界なし'}</span>{fixed&&<span className="fresh">毎回違う依頼</span>}</div><p>{reuse?'共通資料の終わりを保存。次回は同じ部分を再利用できます。':'変わる内容まで保存すると、次回に同じ終点が見つからず再利用できない場合があります。'}</p><Range label="依頼回数" value={runs} min={1} max={30} onChange={setRuns}/></section><section className="lab-panel"><span className="eyebrow">固定部分だけの料金</span><label className="lab-label">比較モデル<select value={model} disabled={call.busy} onChange={e=>{setModel(e.target.value as Model);setKey('');reset()}}>{modelIds.map(m=><option key={m} value={m}>{models[m].name}</option>)}</select></label><div className="frontier-stat">${cached.toFixed(4)}</div><p>毎回通常入力なら ${plain.toFixed(4)}</p><p className="lab-tip">仮定：初回は全量保存、2回目以降は{reuse?'全量ヒット':'毎回全量を新規保存'}。個別の依頼と出力の料金は除外。未ヒット時の一例で、実APIの保証ではありません。</p><p>入力 / 保存 / 再利用：${p.input} / ${p.write} / ${p.read}（100万tok）</p></section></div>
<section className="lab-panel release-section"><span className="eyebrow">02 / 実API · 1回ずつ実行</span><h2>1回目と2回目の利用量を見比べる</h2><p>下の実験では常に共通資料の直後へ保存境界を置きます。上のチェックは仕組みを学ぶ演習専用です。</p><fieldset disabled={call.busy}><label className="lab-label">共通資料<textarea value={prefix} maxLength={50000} onChange={e=>{setPrefix(e.target.value);reset()}}/></label><label className="lab-label">今回の依頼<textarea value={prompt} maxLength={12000} onChange={e=>setPrompt(e.target.value)}/></label></fieldset><KeyInput label={p.provider+' APIキー'} value={key} disabled={call.busy} onChange={s=>{setKey(s);reset()}}/><p className="lab-tip">この実験は共通資料と依頼を選択した提供元に送信します。キーは保存しません。初回から課金されます。出力は4,096トークン、受信90秒まで。キャッシュの最低長・保存期間・提供側の状況でヒットしないことがあります。</p><div className="frontier-actions"><button className="lab-action" disabled={call.busy||!key.trim()||!prefix.trim()||!prompt.trim()} onClick={()=>{const question=prompt;call.run({kind:'text',model,apiKey:key,prefix,prompt,cache:true},r=>setHistory(old=>[...old,{...r,question}].slice(-10)))}}>{call.busy?'応答中…':history.length?'もう1回実行して再利用を確認':'1回目を実行'}</button>{call.busy&&<button className="lab-secondary" onClick={call.stop}>受信を停止</button>}</div>{call.error&&<p role="alert" className="release-message">{call.error}</p>}<p className="lab-tip">初回でも既存のキャッシュにヒットする場合があります。「cold / warm」は決めつけず、実際の保存・再利用トークンで判断します。最大10件を表示。</p>{history.map((r,i)=><article className="frontier-history" key={i}><h3>{i+1}回目：{r.usage?r.usage.read>0?'再利用あり':'再利用なし':'利用量不明'}</h3><p>{r.question}</p><Result result={r}/></article>)}</section>
<section className="lab-panel release-section"><h2>境界の書き方</h2><CopyBlock text={model==='claude-opus-5-5'?JSON.stringify({system:[{type:'text',text:'共通資料',cache_control:{type:'ephemeral'}}]},null,2):JSON.stringify({prompt_cache_options:{mode:'explicit'},input:[{role:'developer',content:[{type:'input_text',text:'共通資料',prompt_cache_breakpoint:{mode:'explicit'}}]},{role:'user',content:'今回の依頼'}]},null,2)}/></section>
</FrontierShell>}
