"use client";
import {useEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import {LabShell,Metric} from '../shared';
import '../releases/release.css';
import './style.css';
export const links=[['/labs/model-comparison','Opus / Sol / Luna'],['/labs/prompt-cache','キャッシュ'],['/labs/llm-typesafe','Jev CLI'],['/labs/gguf','GGUF']];
export function FrontierShell({index,title,lead,sources,children}:{index:number;title:string;lead:string;sources:[string,string][];children:ReactNode}){return <LabShell number={'MODEL NOTES / 0'+(index+1)} title={title} lead={lead} path={links[index][0]} links={links} checked="2026年9月23日" sources={sources}>{children}</LabShell>}
export function useRun(){const [busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),abort=useRef<AbortController|null>(null),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;abort.current?.abort()}},[]);async function run(body:unknown,onResult:(data:any)=>void){if(lock.current)return;lock.current=true;setBusy(true);setError('');abort.current=new AbortController();const timeout=setTimeout(()=>abort.current?.abort(),310000);try{const r=await fetch('/api/labs/frontier',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:abort.current.signal});const data:any=await r.json();if(!r.ok)throw Error(data.error||'実行できませんでした。');if(mounted.current)onResult(data);}catch(e){if(mounted.current)setError(e instanceof Error&&e.name!=='AbortError'?e.message:'受信を停止しました。提供元の処理・課金は続く場合があります。');}finally{clearTimeout(timeout);lock.current=false;if(mounted.current)setBusy(false)}}return {run,busy,error,stop:()=>abort.current?.abort()};}
export function KeyInput({label,value,onChange,disabled}:{label:string;value:string;onChange:(s:string)=>void;disabled:boolean}){return <label className="lab-label">{label}<input type="password" autoComplete="off" maxLength={8192} value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}/></label>}
export function Result({result}:{result:any}){return <><div className="lab-metrics"><Metric label="往復・処理時間" value={result.seconds.toFixed(2)+'秒'}/><Metric label="利用量からの概算" value={result.usd===null?'取得できず':'$'+result.usd.toFixed(6)}/></div>{result.incomplete&&<p className="release-message">{result.limitReached?'出力上限に達しました。上限を増やすか、依頼を分けて再実行してください。':'回答は未完了です。出力上限以外の理由で停止した可能性があります。'}</p>}<p className="lab-tip">{result.incomplete?'未完了':'生成完了'}{result.maxOutput?' / 設定上限 '+result.maxOutput.toLocaleString()+' tok':''}</p><div className="release-output">{result.text}</div>{result.usage&&<p className="lab-tip">通常入力 {result.usage.ordinary} / 保存 {result.usage.write} / 再利用 {result.usage.read} / 出力 {result.usage.output} トークン</p>}</>}
export function download(text:string,name:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
