"use client";
import {useEffect,useState} from 'react';
import {ArrowUpRight,Plus,Globe2,Search,ShoppingBag,Plane,Utensils,Heart,Users,Building2,Pencil,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Skeleton} from '@/components/ui/skeleton';
import {Empty,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
type Site={id:string;name:string;category:string;description:string;tags:string;url:string;status:string};
const categories=['EC・ショッピング','旅行・予約','フード・飲食','SNS・コミュニティ','住まい・不動産','その他'];
const examples:Site[]=[
{id:'sample-1',name:'Mamazon',category:categories[0],description:'商品検索からカート、購入まで。ショッピング体験を検証するデモサイト。',tags:'商品検索,カート,購入',url:'',status:'準備中'},
{id:'sample-2',name:'TripMate',category:categories[1],description:'行きたい場所を見つけて、旅を予約。ホテル・航空券の検索と比較。',tags:'ホテル,航空券,予約',url:'',status:'準備中'},
{id:'sample-3',name:'Umai Eats',category:categories[2],description:'お店選びから注文まで。フードデリバリーの操作をひとつにつなぐ。',tags:'メニュー,注文,配達',url:'',status:'準備中'},
{id:'sample-4',name:'Tappleton',category:categories[3],description:'プロフィールを見つけて、つながる。マッチングサービスのデモ。',tags:'プロフィール,スワイプ',url:'',status:'準備中'},
{id:'sample-5',name:'Fakebook',category:categories[3],description:'投稿、リアクション、コメント。コミュニケーションの流れを試す。',tags:'投稿,ストーリー,通知',url:'',status:'準備中'},
{id:'sample-6',name:'SUUMOじゃ',category:categories[4],description:'条件に合う住まいを探す。物件検索から比較、お問い合わせまで。',tags:'物件検索,比較,問い合わせ',url:'',status:'準備中'}];
const blank:Site={id:'',name:'',category:'その他',description:'',tags:'',url:'',status:'準備中'};
function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full bg-white"><SelectValue/></SelectTrigger><SelectContent>{items.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>}
async function request(method:string,data?:unknown){const res=await fetch('/api/sites',{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const json:any=await res.json();if(!res.ok)throw new Error(json.error||'操作に失敗しました。');return json;}
export default function Home(){
const [sites,setSites]=useState<Site[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('すべて'),[status,setStatus]=useState('すべての状態'),[draft,setDraft]=useState<Site>(blank),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[deleting,setDeleting]=useState<Site|null>(null);
async function load(){setLoading(true);try{setSites(await request('GET'));setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{void load();},[]);
function edit(s:Site=blank){setDraft({...s,id:s.id.startsWith('sample-')?'':s.id});setFormError('');setOpen(true);}
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'search_demo_sites',description:'登録済みデモサイトを検索し、一覧表示を更新する。サンプルは検索結果に含めない。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof (input as any).query!=='string'||(input as any).query.length>200)throw new Error('query must be a string up to 200 characters');const q=(input as any).query;setQuery(q);setCategory('すべて');setStatus('すべての状態');return sites.filter(s=>(s.name+' '+s.description+' '+s.tags).toLowerCase().includes(q.toLowerCase())).map(({id,name,url})=>({id,name,url}));}},{signal:lifecycle.signal})).catch(console.warn);}catch(e){console.warn(e);}return()=>lifecycle.abort();},[sites]);
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setFormError('');try{await request(draft.id?'PUT':'POST',draft);setOpen(false);setQuery('');setCategory('すべて');setStatus('すべての状態');toast.success('サイトを保存しました');await load();}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
async function remove(){if(!deleting)return;setBusy(true);try{await request('DELETE',{id:deleting.id});setDeleting(null);toast.success('登録を削除しました');await load();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
const sample=!loading&&!error&&sites.length===0;
const visible=(sample?examples:sites).filter(s=>(category==='すべて'||s.category===category)&&(status==='すべての状態'||s.status===status)&&[s.name,s.description,s.tags,s.url].join(' ').toLowerCase().includes(query.toLowerCase()));
return <main><header className="topbar"><a className="brand" href="/"><span className="brandmark">a</span>DEMO ATLAS<span className="brand-sub">SITE MANAGEMENT</span></a><span className="workspace">PERSONAL WORKSPACE</span></header>
<section className="intro"><div><div className="eyebrow">YOUR DEMO COLLECTION / 01</div><h1>デモサイトを、<br/><span>ひとつの場所に。</span></h1></div><div className="intro-side"><p>つくる。試す。整理する。<br/>あなたのデモサイトの管理拠点。</p><button className="primary" onClick={()=>edit()}><Plus size={18}/>サイトを追加</button></div></section>
<section className="collection" aria-label="デモサイト一覧"><div className="toolbar"><h2>サイト一覧 <span>{String(sites.length).padStart(2,'0')}</span></h2><div className="flex items-center gap-5 flex-wrap"><label className="search"><Search size={18}/><input aria-label="サイトを検索" placeholder="サイト名・タグで検索" value={query} onChange={e=>setQuery(e.target.value)}/></label><Choice label="状態で絞り込み" value={status} onChange={setStatus} items={['すべての状態','利用中','準備中','休止中']}/></div></div>
<div className="filters" aria-label="カテゴリ">{['すべて',...categories].map(c=><button key={c} className={'filter '+(category===c?'active':'')} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
{error&&<div role="alert" className="notice error">{error}<button onClick={load}>再読み込み</button></div>}
{sample&&<div className="notice"><span>最初のサイトを登録しましょう。下のカードは編集して使えるサンプルです。</span><span>URLは未設定です</span></div>}
{loading?<div className="site-grid" aria-label="読み込み中">{[1,2,3].map(i=><div className="site-card" key={i}><Skeleton className="h-5 w-20 mb-10"/><Skeleton className="h-10 w-40 mb-5"/><Skeleton className="h-16 w-full"/></div>)}</div>:<><p className="result-count" aria-live="polite">{visible.length} {sample?'SAMPLES':'SITES'} / {category==='すべて'?'ALL CATEGORIES':category}</p><div className="site-grid">{visible.map((s,i)=>{const Icon=({[categories[0]]:ShoppingBag,[categories[1]]:Plane,[categories[2]]:Utensils,[categories[3]]:s.name==='Tappleton'?Heart:Users,[categories[4]]:Building2} as any)[s.category]||Globe2;return <article className={'site-card tint-'+(i%6)} key={s.id}><div className="card-top"><span>{String(i+1).padStart(2,'0')} / {sample?'SAMPLE':s.status}</span><Icon size={26} strokeWidth={1.4}/></div><div className="card-main"><p className="category">{s.category}</p><h3>{s.name}</h3><p className="description">{s.description||'説明はまだありません。'}</p></div><div className="tags">{s.tags.split(/[,、]/).map(t=>t.trim()).filter(Boolean).map((t,j)=><span key={j}>{t}</span>)}</div><div className="card-bottom">{sample?<button className="open-site" onClick={()=>edit(s)}>サンプルから登録<Plus size={17}/></button>:<>{s.url?<a className="open-site" href={s.url} target="_blank" rel="noopener noreferrer">サイトを開く<ArrowUpRight size={17}/></a>:<button className="open-site" onClick={()=>edit(s)}>URLを設定<Plus size={17}/></button>}<button className="icon-button" aria-label={s.name+'を編集'} onClick={()=>edit(s)}><Pencil size={16}/></button><button className="icon-button" aria-label={s.name+'を削除'} onClick={()=>setDeleting(s)}><Trash2 size={16}/></button></>}</div></article>})}</div>{!error&&visible.length===0&&<Empty className="empty"><EmptyTitle>一致するサイトがありません</EmptyTitle><EmptyDescription>検索語や絞り込み条件を変更してください。</EmptyDescription><button className="secondary" onClick={()=>{setQuery('');setCategory('すべて');setStatus('すべての状態');}}>絞り込みをクリア</button></Empty>}</>}
</section><footer><span>DEMO ATLAS</span><span>A PLACE FOR EVERY EXPERIMENT.</span></footer>
<Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="modal"><DialogTitle>{draft.id?'サイトを編集':'サイトを登録'}</DialogTitle><DialogDescription>URLは後から設定できます。「保存する」で登録内容を保存します。</DialogDescription><form onSubmit={save} className="form-grid"><label className="field">サイト名 *<input autoFocus required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="例：Mamazon"/></label><label className="field">URL<input type="url" maxLength={2048} value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})} placeholder="https://example.com"/></label><div className="field">カテゴリ<Choice label="カテゴリを選択" value={draft.category} onChange={v=>setDraft({...draft,category:v})} items={categories}/></div><label className="field">説明<textarea maxLength={500} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="どんな操作を試せるサイトですか？"/></label><label className="field">タグ（カンマ区切り）<input maxLength={200} value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})} placeholder="検索, カート, 購入"/></label><div className="field">管理状態<Choice label="管理状態を選択" value={draft.status} onChange={v=>setDraft({...draft,status:v})} items={['利用中','準備中','休止中']}/></div>{formError&&<p className="notice error" role="alert">{formError}</p>}<div className="form-buttons"><button className="secondary" type="button" disabled={busy} onClick={()=>setOpen(false)}>キャンセル</button><button className="primary" disabled={busy} type="submit">{busy?'保存中…':'保存する'}</button></div></form></DialogContent></Dialog>
<AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!busy)setDeleting(null);}}><AlertDialogContent><AlertDialogTitle>「{deleting?.name}」の登録を削除しますか？</AlertDialogTitle><AlertDialogDescription>この一覧から削除されます。リンク先のサイト自体は削除されません。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>キャンセル</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={busy} onClick={e=>{e.preventDefault();void remove();}}>{busy?'削除中…':'削除する'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster position="bottom-right"/>
</main>}


