import type {Scenario,Evaluation} from './types.ts';
export const scenarios:Record<string,Scenario>={
 support:{id:'support',name:'問い合わせ判定',title:'問い合わせを、3つの判断に。',description:'担当部署・緊急性・不満の強さをまとめて判定します。',inputLabel:'問い合わせ文',rubric:'担当部署は技術・請求・営業の3択。緊急性は期限や損失、即時対応の必要性。不満は文章の語調を0〜2で評価します。',disclaimer:'返信や担当者への転送は行いません。',
 samples:[{label:'接続トラブル',text:'決済サービスとの連携が3日前から何度試しても失敗します。販売を再開できず、売上に影響が出ています。早急に調査して対応してください。'},{label:'二重請求',text:'今月の利用料金がカード明細に2回記載されていました。重複分の確認と返金をお願いできますか。'},{label:'プランの相談',text:'チームでの導入を検討しています。10名で利用する場合のプランと、年間契約の料金を教えてください。'}],
 choice:{key:'department',label:'担当部署',instructions:'Determine which support team should handle this customer message.',options:{technical:'技術サポート',billing:'請求・支払い',sales:'営業・契約'},criteria:{technical:'Product bugs, outages or integration issues.',billing:'Payments, invoices, refunds or duplicate charges.',sales:'Pricing, plans or pre-purchase questions.'}},
 score:{key:'frustration',label:'不満の強さ',instructions:'Rate the frustration expressed in the tone, not severity of the issue.',criteria:['Calm or neutral.','Frustrated but civil.','Very angry or strongly upset.'],scale:'0：平静 / 1：不満 / 2：強い怒り'},
 noul:{key:'is_urgent',label:'緊急性がある確率',instructions:'Does the message express urgency or time sensitivity?',yes:'A deadline, ongoing loss or need for immediate help is stated.',no:'No time sensitivity is expressed.'},sample:{choice:'technical',probabilities:{technical:.94,billing:.04,sales:.02},scoreProbabilities:[.03,.82,.15],noul:.97}},
 reviews:{id:'reviews',name:'レビュー分析',title:'レビューから、改善のヒントを。',description:'感情の傾向・満足度・個別フォローの必要性を読み取ります。',inputLabel:'商品・サービスのレビュー',rubric:'感情は肯定・賛否混在・否定・中立の4択。満足度は0（とても不満）〜4（とても満足）。フォローは未解決の問題や対応要求の有無で評価します。',disclaimer:'レビューへの返信や公開操作は行いません。',
 samples:[{label:'改善要望あり',text:'デザインと操作性には満足しています。ただ、データの書き出しでエラーが続き、仕事で使えません。サポートに連絡しましたがまだ返答がないため、早めに解決してほしいです。'},{label:'高評価',text:'設定が簡単で、毎週の集計が30分から5分になりました。サポートも親切で、同僚にもすすめたいです。今のところ困っていることはありません。'},{label:'中立的な感想',text:'商品は予定日に届きました。サイズは説明どおりです。まだ数回しか使っていないので、耐久性についてはこれから確認します。'}],
 choice:{key:'sentiment',label:'レビューの傾向',instructions:'Classify the overall sentiment expressed in this review.',options:{positive:'肯定的',mixed:'賛否が混在',negative:'否定的',neutral:'中立・判断材料不足'},criteria:{positive:'Predominantly positive appraisal.',mixed:'Substantial praise and complaints coexist.',negative:'Predominantly negative appraisal.',neutral:'Descriptive, neutral, or insufficient evidence.'}},
 score:{key:'satisfaction',label:'満足度',instructions:'Rate overall customer satisfaction expressed in the review. Infer only from the supplied text.',criteria:['Very dissatisfied.','Mostly dissatisfied.','Mixed or neutral satisfaction.','Mostly satisfied.','Very satisfied.'],scale:'0：とても不満 / 2：中立 / 4：とても満足'},
 noul:{key:'needs_followup',label:'フォローが必要な確率',instructions:'Does this review indicate an unresolved issue requiring individual customer support?',yes:'An unresolved defect, complaint or explicit request for support is present.',no:'No unresolved issue requiring support is expressed.'},sample:{choice:'mixed',probabilities:{positive:.04,mixed:.88,negative:.06,neutral:.02},scoreProbabilities:[.02,.18,.65,.13,.02],noul:.96}},
 leads:{id:'leads',name:'営業リード判定',title:'商談の温度感を、見える形に。',description:'検討段階・導入意欲・デモ提案の適切さを判定します。',inputLabel:'問い合わせ・商談メモ',rubric:'検討段階は情報収集・比較検討・導入直前・不明の4択。導入意欲は0〜4。デモ提案の適切さは要件確認や具体的な相談の有無から評価します。',disclaimer:'顧客への連絡や営業活動は実行しません。',
 samples:[{label:'具体的な導入相談',text:'営業チーム20名での導入を検討しています。来月から利用したく、予算は月10万円程度です。他社サービスと比較しており、既存CRMとの連携方法をデモで見せていただけますか。決裁者も同席します。'},{label:'情報収集',text:'業界調査のため、製品の機能一覧と料金表を送ってください。導入時期や予算はまだ決まっておらず、現時点では打ち合わせは不要です。'},{label:'契約の最終確認',text:'社内承認が完了しました。50アカウントで年間契約したいので、申込書と契約開始日について案内をお願いします。デモはすでに確認済みです。'}],
 choice:{key:'stage',label:'検討段階',instructions:'Identify the buyer journey stage expressed by this prospect.',options:{research:'情報収集',comparison:'比較検討',ready:'導入直前',unknown:'情報不足'},criteria:{research:'Gathering information without concrete purchase planning.',comparison:'Evaluating vendors, requirements, budgets or demos.',ready:'Approval complete or explicit request to purchase or contract.',unknown:'Insufficient evidence of a buying stage.'}},
 score:{key:'intent',label:'導入意欲',instructions:'Rate purchase intent based only on explicit evidence such as budget, timeline, authority and commitment.',criteria:['No expressed purchase interest.','General curiosity.','Active evaluation, commitment unclear.','Concrete requirements and timeline.','Explicit commitment to purchase or approved contract.'],scale:'0：関心なし / 2：検討中 / 4：導入意思あり'},
 noul:{key:'demo_fit',label:'デモ提案が適切な確率',instructions:'Would proposing a product demo be appropriate as the next step for this prospect?',yes:'Demo requested or concrete questions would benefit from a demo.',no:'Meeting declined, no buying interest, or demo already completed and contract requested.'},sample:{choice:'comparison',probabilities:{research:.02,comparison:.94,ready:.03,unknown:.01},scoreProbabilities:[0,.01,.12,.81,.06],noul:.98}},
 tasks:{id:'tasks',name:'タスク優先度判定',title:'依頼文から、対応の順番を。',description:'優先度・業務への影響・期限の有無を判定します。',inputLabel:'タスク・依頼の内容',rubric:'優先度は低・通常・高・最優先の4択。影響度は0（影響なし）〜4（広範な重大影響）。期限は文章に日付・相対的な期限・時間制約が明記されているかを判定します。',disclaimer:'タスクの登録や担当者への割り当ては行いません。',
 samples:[{label:'サービス障害',text:'本番環境でログインできない障害が発生し、全ユーザーがサービスを利用できません。現在も継続しています。30分以内に一次対応を開始し、状況を共有してください。'},{label:'通常の改善',text:'次の定例会で使う資料のグラフを見やすくしてください。現行の資料でも説明はできるので、他の作業に支障がなければ対応をお願いします。'},{label:'期限付きの確認',text:'金曜日の17時までにキャンペーンの掲載内容を確認してください。確認が終わらないと翌週の公開を開始できません。影響するのは今回のキャンペーンだけです。'}],
 choice:{key:'priority',label:'対応優先度',instructions:'Assign operational task priority based on stated impact, urgency and blockers. Avoid escalating solely due to emphatic wording.',options:{low:'低',normal:'通常',high:'高',critical:'最優先'},criteria:{low:'Optional improvement with little impact and no pressing time constraint.',normal:'Routine work with manageable impact.',high:'Significant deadline or blocker requiring prompt attention.',critical:'Ongoing broad outage or severe business interruption requiring immediate action.'}},
 score:{key:'impact',label:'業務への影響度',instructions:'Rate the scope and severity of business impact explicitly described in the task.',criteria:['Negligible impact.','Minor inconvenience to an individual.','Limited team or workflow disruption.','Major disruption to an important workflow.','Widespread outage or severe core business interruption.'],scale:'0：影響なし / 2：限定的 / 4：重大な影響'},
 noul:{key:'has_deadline',label:'明示的な期限がある確率',instructions:'Does the task explicitly state a date, relative deadline or time limit? Do not infer a deadline from importance alone.',yes:'A date, before-event requirement, relative deadline or time limit is explicitly stated.',no:'No explicit time limit or deadline is present.'},sample:{choice:'critical',probabilities:{low:0,normal:.01,high:.04,critical:.95},scoreProbabilities:[0,0,.01,.08,.91],noul:.99}}
};
export const scenarioIds=['support','reviews','leads','tasks'] as const;
export function scenarioPath(id:string){return id==='support'?'/jev':'/jev/'+id;}
export function sampleEvaluation(s:Scenario):Evaluation {
 const distribution=Object.fromEntries(s.sample.scoreProbabilities.map((p,i)=>[String(i),p]));
 return {model:'表示用サンプル（API未実行）',answers:{
  [s.choice.key]:{type:'choice',choice:s.sample.choice,confidence:.8,probabilities:s.sample.probabilities},
  [s.score.key]:{type:'score',score:s.sample.scoreProbabilities.reduce((sum,p,i)=>sum+p*i,0),confidence:.8,legend:Object.fromEntries(s.score.criteria.map((label,i)=>[String(i),label])),probabilities:distribution},
  [s.noul.key]:{type:'noul',noul:s.sample.noul}
 }};
}
