"use client";
import {useState} from 'react';
import {FrontierShell,KeyInput,useRun,Result} from '../frontier/shared';
import {models,modelIds,Model} from '../frontier/data';
import {Range} from '../shared';
export default function Page(){const [prompt,setPrompt]=useState('送料の仕様：購入額5,000円以上は無料、未満は500円。負の金額はエラー。現在のコードは amount > 5000 ? 0 : 500 です。問題点と修正コード、境界値テスト3件を日本語で簡潔に示し、最後に仕様を満たすか自己確認してください。'),[anthropic,setAnthropic]=useState(''),[openai,setOpenai]=useState(''),[maxOutput,setMaxOutput]=useState(16384),[tokens,setTokens]=useState(10000),[output,setOutput]=useState(1000),[results,setResults]=useState<Partial<Record<Model,any>>>({});const call=useRun();return <FrontierShell index={0} title="同じ依頼。3つの答え。" lead="Opus 5.5・GPT-6 Sol・Luna。料金を動かして比較し、同じ依頼への回答を自分の基準で確かめます。" sources={[['Anthropic / Opus 5.5','https://www.anthropic.com/claude-opus-5-5'],['OpenAI / Sol・Luna','https://openai.com/index/introducing-gpt-6-sol-and-luna'],['OpenAI / 料金','https://developers.openai.com/api/docs/pricing'],['Claude / モデル仕様','https://platform.claude.com/docs/en/models/overview']]}>
<section className="lab-panel"><span className="eyebrow">01 / 料金を比べる · 計算デモ</span><h2>この仕事を1回頼むと？</h2><div className="lab-grid"><Range label="入力の量" value={tokens} min={1000} max={50000} step={1000} onChange={setTokens} unit=" tok"/><Range label="出力の量" value={output} min={500} max={10000} step={500} onChange={setOutput} unit=" tok"/></div><p className="lab-tip">標準処理・キャッシュなしの目安。回答の品質や速度を推定するものではありません。出力には推論トークンも含まれます。</p></section>
<div className="frontier-three">{modelIds.map(id=><article className="lab-panel" key={id}><span className="eyebrow">{models[id].provider}</span><h2>{models[id].name}</h2><p>{models[id].note}</p><div className="frontier-price">${((tokens*models[id].input+output*models[id].output)/1e6).toFixed(4)} <small>/ 1回</small></div><p className="lab-tip">100万トークンあたり 入力 ${models[id].input} / 出力 ${models[id].output}</p></article>)}</div>
<div className="frontier-note">Opus 5.5は最大1Mの文脈・128Kの出力に対応し、思考をオフにはできません。Fast modeは公式価格が入力$8 / 出力$40、最大2.5倍速。このデモの実行は標準モードです。速度の向上は公式発表であり、このサイトでの実測ではありません。</div>
<section className="lab-panel release-section"><span className="eyebrow">02 / 実モデルで比較</span><h2>依頼をそろえて、回答を並べる</h2><label className="lab-label">3モデル共通の依頼<textarea value={prompt} maxLength={12000} disabled={call.busy} onChange={e=>{setPrompt(e.target.value);setResults({})}}/></label><label className="lab-label">実行時の出力上限（内部の推論を含む）<select value={maxOutput} disabled={call.busy} onChange={e=>{setMaxOutput(Number(e.target.value));setResults({})}}><option value={8192}>8,192トークン — 短い回答</option><option value={16384}>16,384トークン — 標準</option><option value={32768}>32,768トークン — 長い回答</option></select></label><p className="lab-tip">回答が途中で終わる場合は上限を増やして再実行してください。上限を増やすと、実際の使用量に応じて料金と時間が増える場合があります。上の料金スライダーは試算専用です。</p><div className="lab-grid"><KeyInput label="Anthropic APIキー（Opus用）" value={anthropic} onChange={setAnthropic} disabled={call.busy}/><KeyInput label="OpenAI APIキー（Sol・Luna用）" value={openai} onChange={setOpenai} disabled={call.busy}/></div><p className="lab-tip">押したモデルにだけ依頼文を送信します。キーは保存しません。各実行は有料、受信期限5分。依頼や出力上限を変えると比較結果を消去します。</p><div className="frontier-actions">{modelIds.map(model=><button key={model} className="lab-action" disabled={call.busy||!prompt.trim()||!(model==='claude-opus-5-5'?anthropic:openai).trim()} onClick={()=>call.run({kind:'text',model,prompt,maxOutput,apiKey:model==='claude-opus-5-5'?anthropic:openai},r=>setResults(old=>({...old,[model]:r})))}>{models[model].name}に依頼</button>)}{call.busy&&<button className="lab-secondary" onClick={call.stop}>受信を停止</button>}</div>{call.busy&&<p role="status">実モデルが応答中です…</p>}{call.error&&<p role="alert" className="release-message">{call.error}</p>}</section>
<div className="frontier-three">{modelIds.map(model=><section className="lab-panel" key={model}><h2>{models[model].name}</h2>{results[model]?<Result result={results[model]}/>:<p className="release-empty">まだ実行していません。</p>}</section>)}</div><p className="lab-tip">比較の観点：①5,000円ちょうど ②負の金額 ③テストと自己確認。所要時間は通信・推論を含み、1回の結果でモデル全体の優劣は決まりません。概算料金は保存・再利用を含む標準単価です。</p>
</FrontierShell>}
