"use client";
import {useState,useEffect,useRef} from 'react';
import type {ReactNode} from 'react';
import {LabShell,CopyBlock} from '../shared';
import '../releases/release.css';
import './news.css';
export const newsLinks=[['/labs/jev-gateway','Jev / Gateway'],['/labs/bedrock','Grok / Bedrock'],['/labs/copilot','Grok / Copilot'],['/labs/mimo','MiMo / 公開ウェイト']];
export function NewsShell({index,title,lead,children,sources}:{index:number;title:string;lead:string;children:ReactNode;sources:[string,string][]}){return <LabShell number={'SEP 23 / 0'+(index+1)} title={title} lead={lead} path={newsLinks[index][0]} links={newsLinks} checked="2026年9月23日" sources={sources}>{children}</LabShell>}
export function useCall(){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null);const lock=useRef(false),controller=useRef<AbortController|null>(null),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort()}},[]);async function run(body:unknown){if(lock.current)return;lock.current=true;setBusy(true);setError('');setResult(null);controller.current=new AbortController();const timer=setTimeout(()=>controller.current?.abort(),100000);try{const r=await fetch('/api/labs/news',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.current.signal});const data:any=await r.json();if(!r.ok)throw Error(data.error||'実行できませんでした。');if(mounted.current)setResult(data);}catch(e){if(mounted.current)setError(e instanceof Error&&e.name==='AbortError'?'受信を終了しました。提供元の処理・課金は続く場合があります。':e instanceof Error?e.message:'接続できませんでした。');}finally{clearTimeout(timer);lock.current=false;if(mounted.current)setBusy(false)}}return {busy,error,result,run,stop:()=>controller.current?.abort()};}
export function TextTrial({provider,config,keyLabel,description,initialPrompt}:{provider:'bedrock'|'mimo';config:Record<string,string>;keyLabel:string;description:string;initialPrompt:string}){const [prompt,setPrompt]=useState(initialPrompt),[key,setKey]=useState(''),[snapshot,setSnapshot]=useState<any>(null);const call=useCall();return <div className="lab-grid"><section className="lab-panel"><h2>実モデルへ依頼する</h2><label className="lab-label">依頼文<textarea value={prompt} disabled={call.busy} maxLength={12000} onChange={e=>setPrompt(e.target.value)}/></label><label className="lab-label">{keyLabel}<input type="password" value={key} disabled={call.busy} autoComplete="off" maxLength={8192} onChange={e=>setKey(e.target.value)}/></label><p className="lab-tip">{description} キーは保存しません。実行時にAPI料金が発生します。出力は最大4,096トークン、受信は90秒までです。</p><button className="lab-action" disabled={call.busy||!key.trim()||!prompt.trim()} onClick={()=>{setSnapshot({prompt,...config});call.run({provider,prompt,apiKey:key,...config})}}>{call.busy?'実モデルが応答中…':'この設定で実行'}</button>{call.busy&&<button className="lab-secondary" onClick={call.stop}>受信を停止</button>}</section><section className="lab-panel"><h2>今回の実行結果</h2>{call.error&&<p role="alert" className="release-message">{call.error}</p>}{call.result?<><div className="lab-notice">{call.result.model} · {call.result.seconds.toFixed(2)}秒{call.result.incomplete?' · 出力上限などで未完了':''}</div><div className="release-output">{call.result.text}</div><details><summary>実行時の設定と利用量</summary><CopyBlock text={JSON.stringify({settings:snapshot,usage:call.result.usage},null,2)} label="実行情報をコピー"/></details></>:<div className="release-empty">APIキーを入力すると実際の回答を表示します。設定だけで性能や料金が測定されたことにはなりません。</div>}</section></div>}
