"use client";
import {useState} from 'react';
import type {ReactNode} from 'react';
import {ArrowLeft,ArrowUpRight,Copy,Check} from 'lucide-react';
import '../jev/jev.css';
import './labs.css';
export const labLinks=[['/qwen-image/comfyui','ComfyUI'],['/qwen-image/inference','推論の高速化'],['/qwen-image/prompt-rewrite','プロンプト書き換え'],['/jev/evals','Jevの評価比較']];
export function LabShell({number,title,lead,path,children,sources,links=labLinks,checked="2026年9月21日"}:{number:string;title:string;lead:string;path:string;children:ReactNode;sources:[string,string][];links?:string[][];checked?:string}){return <main className="jev-page learn-lab"><header className="topbar"><a className="brand" href="/"><span className="brandmark">a</span>DEMO ATLAS</a><a className="jev-back" href="/"><ArrowLeft size={16}/>サイト一覧へ</a></header><nav className="lab-nav" aria-label="関連デモ">{links.map(([url,label])=><a key={url} href={url} aria-current={url===path?'page':undefined}>{label}</a>)}</nav><section className="lab-heading"><span className="eyebrow">INTERACTIVE NOTES / {number}</span><h1>{title}</h1><p>{lead}</p></section>{children}<section className="lab-sources"><h2>公式資料</h2><p>{checked}に確認。実行条件や対応バージョンは各資料を確認してください。</p><nav>{sources.map(([label,url])=><a key={url} href={url} target="_blank" rel="noopener noreferrer">{label}<ArrowUpRight size={14}/></a>)}</nav></section><footer><span>DEMO ATLAS / LEARN BY DOING</span><span>2026.09</span></footer></main>}
export function CopyBlock({text,label='設定をコピー'}:{text:string;label?:string}){const [status,setStatus]=useState('');return <div className="lab-code"><pre>{text}</pre><button onClick={async()=>{try{await navigator.clipboard.writeText(text);setStatus('コピーしました')}catch{setStatus('コピーできません。文章を選択してコピーしてください。')}}}>{status==='コピーしました'?<Check size={15}/>:<Copy size={15}/>} {label}</button>{status&&<p role="status">{status}</p>}</div>}
export function Range({label,value,min,max,step=1,onChange,unit=''}:{label:string;value:number;min:number;max:number;step?:number;onChange:(value:number)=>void;unit?:string}){return <label className="lab-range"><span>{label}<b>{value}{unit}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
export function Metric({label,value,note}:{label:string;value:string;note?:string}){return <div className="lab-metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
